### Made by Guillermo Zaandam

### Command 1: 'ansible-playbook -i 192.168.122.194, ansibleplaybook.yml --ask-become-pass'
### Command 2: 'ansible-playbook  ansibleplaybook.yml --ask-become-pass'

### command 2 is default for this playbook and you can use it directly to install and configure the software.


- name: My first play
  hosts: localhost #all # "'all' is used for testing this playbook delete 'localhost' and change it to 'all' and use command 1 and change the ip address to test this playbook."
  become: yes

  tasks:
     - name: Update apt cache
       apt:
         update_cache: yes
       become: yes
    
     - name: Install required packages
       apt:
         name:
           - gnupg2
           - pass
           - shellcheck
           - elinks
           - autossh
           - surfraw
           - surfraw-extra
           - googler
           - jpegoptim
           - ffmpeg
           - gnome-tweaks
           - gnome-shell-extensions
           - thunderbird
           - software-properties-common
           - gimp
           - scribus
           - krita
           - darktable
           - graphviz
           - docker
           - docker-compose
           - google-chrome-stable
           - chrome-gnome-shell
           - peek
           - lollypop
           - shotwell
           - gnome-firmware
           - remmina
           - transmission
           - deja-dup
           - ansible
           - tlp
           - tlp-rdw
           - dislocker
           - neovim
           - gnome-books
           - guake
           - gpick
           - mosh
           - autokey-gtk
           - aria2
           - asciinema
           - ttyrec
         state: present
       become: yes

     - name: Install virt-manager, libguestfs-tools, and gnome-boxes
       apt:
         name:
           - virt-manager
           - libguestfs-tools
           - gnome-boxes
         state: present
       become: yes
 
     - name: Install qemu, qemu-kvm, and bridge-utils
       apt:
         name:
           - qemu
           - qemu-kvm
           - bridge-utils
         state: present
       become: yes
 
     - name: Download .deb Package
       get_url:
         url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64" #"URL_TO_YOUR_DEB_PACKAGE"
         dest: "/tmp/code_1.81.1-1691620686_amd64"  # Destination path on the remote server # mostly the tmp folder. 

     - name: Install .deb Package
       apt:
         deb: "/tmp/code_1.81.1-1691620686_amd64"
         state: present  # This ensures the package is installed # mostly the tmp folder.